# Generated by Django 5.2.1 on 2025-05-23 12:09

import django.db.models.deletion
import django_ckeditor_5.fields
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(default=1, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='shop/category/images')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('slug', models.CharField(blank=True, max_length=255, null=True, verbose_name='ЧПУ')),
                ('short_description', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('html_content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='SEO текст')),
                ('display_amount', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('order_num',),
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(default=1, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='shop/category/images')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('slug', models.CharField(blank=True, max_length=255, null=True, verbose_name='ЧПУ')),
                ('short_description', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('html_content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='SEO текст')),
            ],
            options={
                'verbose_name': 'Стиль',
                'verbose_name_plural': 'Стиль',
                'ordering': ('order_num',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(default=1, null=True)),
                ('article', models.CharField(blank=True, max_length=20, null=True, verbose_name='Артикул')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна производства')),
                ('delivery', models.CharField(blank=True, max_length=100, null=True, verbose_name='Срок поставки')),
                ('unit', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фасовка')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('is_in_stock', models.BooleanField(default=True, verbose_name='В наличии?')),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('slug', models.CharField(blank=True, editable=False, help_text='Если не заполнено, создается на основе поля Назавание', max_length=255, null=True, verbose_name='ЧПУ')),
                ('short_description', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('editor_1', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Свойства')),
                ('editor_2', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Применеие')),
                ('editor_3', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Состав')),
                ('editor_4', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Доствка')),
                ('editor_5', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Результат')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.category')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('order_num',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=95, scale=None, size=[650, 570], upload_to='shop/product/images')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основное')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product')),
            ],
            options={
                'verbose_name': 'Доп. изображение товара',
                'verbose_name_plural': 'Доп. изображения товара',
            },
        ),
        migrations.CreateModel(
            name='StyleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(default=1, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('style', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.style')),
            ],
            options={
                'verbose_name': 'Товар стиля',
                'verbose_name_plural': 'Товар стиля',
                'ordering': ('order_num',),
            },
        ),
    ]
