# Generated by Django 5.2.1 on 2025-05-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_country_remove_product_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='style',
            field=models.CharField(default='col-span-12 md:col-span-4', help_text='col-span-12 md:col-span-9 md:col-start-4, col-span-12 md:col-span-4 md:col-start-2, col-span-12 md:col-span-4 md:col-start-9col-span-12 md:col-span-6', max_length=255),
        ),
    ]
