# Generated by Django 5.2.1 on 2025-05-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_style_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='short_description',
        ),
    ]
