# Generated by Django 5.2.1 on 2025-06-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_style_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='styles',
            field=models.ManyToManyField(blank=True, to='shop.style'),
        ),
    ]
