# Generated by Django 5.2.1 on 2025-07-04 14:20

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_category_styles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=95, scale=None, size=[1500, 1500], upload_to='shop/product/images'),
        ),
    ]
