# Generated by Django 5.2.1 on 2025-07-31 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inner_id',
            field=models.CharField(blank=True, default=1, max_length=50, null=True),
        ),
    ]
