# Generated by Django 5.2.1 on 2025-09-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_delivery_type_alter_order_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='order',
            name='selected_delivery',
            field=models.TextField(blank=True, null=True, verbose_name='доставка'),
        ),
    ]
