# Generated by Django 5.2.1 on 2025-10-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_delivery_type_remove_order_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sdek_at_door',
            field=models.BooleanField(default=False, verbose_name='СДЕК до двери'),
        ),
    ]
